name: Update GitHub Readme Stats

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC
  workflow_dispatch:    # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p profile

      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=jamesfredley&rank_icon=percentile&show_icons=true&theme=tokyonight&show=reviews,prs_merged&bg_color=fff&title_color=0a1931&icon_color=0a1931&text_color=0A0209&border_color=0A0209&border_radius=8&hide=stars
          path: profile/stats.svg
          token: ${{ secrets.GH_TOKEN }}  # Your PAT (recommended); fallback to ${{ secrets.GITHUB_TOKEN }} for basic public stats

      - name: Commit and Push Card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub stats card" || exit 0
          git push
